# Basic project info
sonar.projectKey=miskcity
sonar.projectName=miskcity
sonar.projectVersion=1.0

# Root folder for project
sonar.projectBaseDir=.

# Only scan custom code
sonar.sources=web/modules/custom,web/themes/custom

# Exclusions (recommended for Drupal)
sonar.exclusions=web/core/**,web/modules/contrib/**,vendor/**,**/*.min.js,**/*.css,**/*.twig,web/modules/custom/**/js/*.js,web/modules/custom/**/js/*.min.js,web/modules/custom/**/css/*.css,web/modules/custom/**/css/*.min.css,web/themes/custom/**/assets/src/js/*.js,web/themes/custom/**/assets/src/js/*.min.js,web/themes/custom/**/*.js

# PHPUnit coverage file
sonar.php.coverage.reportPaths=coverage/clover.xml

# Test file locations
sonar.tests=web/modules/custom
sonar.test.inclusions=**/*Test.php

# Encoding
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5

sonar.issue.ignore.multicriteria.e1.ruleKey=php:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php

sonar.issue.ignore.multicriteria.e2.ruleKey=php:S1448
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.php

sonar.issue.ignore.multicriteria.e3.ruleKey=php:S107
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.php

sonar.issue.ignore.multicriteria.e4.ruleKey=php:S5332
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.php

# If you REALLY need .inc support
sonar.issue.ignore.multicriteria.e5.ruleKey=php:S100
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.inc