<?php

use Drupal\taxonomy\Entity\Term;

function city_map_theme($existing, $type, $theme, $path)
{
  $module_path = \Drupal::service('extension.list.module')->getPath('city_map') . '/templates';

  return [
    'city_map' => [
      'template' => 'city-map',
    ]
  ];
}


function city_map_preprocess_city_map(&$variables)
{
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('map_poi_s');

  $full_terms = [];
  foreach ($terms as $term_info) {
    $term_entity = Term::load($term_info->tid);
    if ($term_entity) {
      $full_terms[] = $term_entity;
    }
  }

  $variables['taxonomy_terms'] = $full_terms;
}
