career-apply-form-library:
  js:
    # External jQuery Validate
    https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js:
      type: external
      minified: true
    # Your custom validation JS
    js/career-apply-form.js: {}
  dependencies:
    - core/jquery
    - core/drupalSettings
